import {
  timestamp,
  files,
  shell,
  routes
} from "../__sapper__/service-worker.js";

const ASSETS = `cache${timestamp}`;

// `shell` is an array of all the files generated by webpack,
// `files` is an array of everything in the `static` directory
const to_cache = shell.concat(ASSETS);
const cached = new Set(to_cache);

self.addEventListener("install", event => {
  // Skip initial cache for now. I want to get things working first
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys().then(async keys => {
      // delete old caches
      for (const key of keys) {
        if (key !== ASSETS) await caches.delete(key);
      }

      self.clients.claim();
    })
  );
});

self.addEventListener("fetch", event => {
  // Skip all fetching for now. I've been hitting a few errors and I want
  // to get "Install app" working correctly
});
